version: "3.7"

services:
  app:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
      args:
        - POETRY_VERSION=1.7.1
    volumes:
      - ../..:/workspaces:cached
    command: sleep infinity
    networks:
      - dope_net

networks:
  dope_net:
    driver: bridge
